# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'source/VirtualDesktop.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '-c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: '$(solution)'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    nobuild: true
    versioningScheme: 'off'
    arguments: '-c $(buildConfiguration)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))

- task: PublishBuildArtifacts@1
  displayName: 'publish artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
